services:
  - type: static
    name: PRIME Drinks project
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: "Cache-Control"
        value: "no-cache"
    redirects:
      - source: "/*"
        destination: "/index.html"
        statusCode: 200
